
# Create build dir
#
cd myProject
mkdir build
cd build
cmake ..

# Check build
#
make

# Check documentation (generated by Doxygen)
# (open myProject/build/doc/doxygen/index.html with your web browser)
#
make doc

# Check (local) install
#
make DESTDIR=local_install install

# check test 
#
make test

# ctest (+ cdash board)
# 
ctest -D Experimental
