
# Create build dir
#
cd superProject
mkdir build
cd build
cmake ..

# Check build
#
make

# check documentation (generated by Doxygen)
#
make doc

# check (local) install
#
make DESTDIR=local_install install

# check test 
#
make test

# ctest (+ cdash board)
# -> create a cdash board before
# ctest -D Experimental
